//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by GuiTest3.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDB_WRITESMALL                  110
#define IDB_WRITELARGE                  111
#define IDB_MAIN                        112
#define IDB_BUTTONS                     113
#define IDB_FILELARGE                   114
#define IDB_FILESMALL                   115
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_GuiTest3TYPE                130
#define ID_WINDOW_MANAGER               131
#define IDS_STATUS_PANE3                132
#define ID_VIEW_IPADDRVIEW              133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define IDR_PASTE_MENU                  151
#define ID_SORTPROPERTIES               151
#define IDR_WINDOWS_MENU                152
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define ID_TOOLS_OPTIONS                220
#define ID_VIEW_CAPTION_BAR             221
#define IDB_INFO                        230
#define IDS_CAPTION_BUTTON              231
#define IDS_CAPTION_BUTTON_TIP          232
#define IDS_CAPTION_TEXT                233
#define IDS_CAPTION_IMAGE_TIP           234
#define IDS_CAPTION_IMAGE_TEXT          235
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDR_RIBBON                      307
#define ID_FILE_SAVE_DB                 310
#define IDR_DBVIEW_OBJECT_POPUP         311
#define ID_DB_DOCKVIEW                  311
#define ID_BUTTON_TIPS2                 312
#define ID_TOGGLE_GRID                  313
#define IDR_TREE_ROOT                   314
#define IDR_SERVICES_STATE              315
#define IDD_ADDPREFIX                   316
#define IDB_IPTREE_VIEW_24              318
#define IDB_IPTREE_VIEW                 320
#define IDR_IPTREEVIEW                  321
#define IDB_IPTREENODE_24               324
#define IDR_POPUP_IPTREEVIEW            325
#define ID_COPYPREFIX                   514
#define ID_VIEW_INETP                   515
#define IDC_BREADCRUMB                  516
#define IDC_ASN                         1000
#define IDC_VALUE                       1001
#define IDC_IPADDRESS                   1002
#define IDC_PREFIXLENGTH                1003
#define IDC_INTERFACEUID                1004
#define ID_WRITE_PASTEASHYPERLINK       32770
#define ID_ADDNODE                      32771
#define ID_BUTTON4                      32773
#define ID_NEWLINK                      32773
#define ID_BUTTON5                      32774
#define ID_EDITGROUP                    32774
#define ID_BUTTON6                      32775
#define ID_SPF_RUN                      32775
#define ID_BUTTON7                      32776
#define ID_SPF_ATTR_WEIGHT              32776
#define ID_BUTTON8                      32777
#define ID_SPF_ATTR_LATENCY             32777
#define ID_BUTTON9                      32778
#define ID_SPF_ATTR_HOPCOUNT            32778
#define ID_BUTTON10                     32779
#define ID_PROPBACK                     32780
#define ID_BUTTON32781                  32781
#define ID_PROPNEXT                     32781
#define ID_NEWFLOW                      32786
#define ID_NEWDEMAND                    32787
#define ID_EDITLAYERS                   32788
#define ID_NEWNODE                      32789
#define ID_GRAPH_TOOLTIPS               32792
#define ID_OBJECTMENU_SHOWONMAP         32793
#define ID_OBJECTMENU_DELETE            32794
#define ID_SCROLL_SELECT                32795
#define ID_STICKY_SELECT                32796
#define ID_REFRESH_TREE                 32797
#define ID_TREE_DELETE                  32798
#define ID_TABLEMENU_TODOTREETABLEMENU  32799
#define ID_SPF_ATTRIBUTE                32800
#define ID_SPF_CONSTRAINTS              32801
#define ID_COMBO2                       32802
#define ID_COMBO3                       32803
#define ID_BUTTON12                     32806
#define ID_BUTTON2                      32808
#define ID_UPGROUP                      32808
#define ID_BUTTON3                      32809
#define ID_GLOBAL_GROUP                 32809
#define ID_BUTTON11                     32810
#define ID_BUTTON13                     32811
#define ID_BUTTON14                     32812
#define ID_BUTTON15                     32813
#define ID_ENABLEOBJECT                 36814
#define ID_SORTING_SORTBYTYPE36816      36816
#define ID_SHOWONMAP                    36818
#define ID_OBJECTMENU_OBJECT_INSERVICE  36819
#define ID_REFRESH_SERVICES             36819
#define ID_CHECK2                       36820
#define ID_CHECK5                       36824
#define ID_REFRESH                      36825
#define ID_ADDPREFIX                    36826
#define ID_EDITPREFIX                   36827
#define ID_DELETEPREFIX                 36828
#define ID_EXPANDALL                    36829
#define ID_COLLAPSEALL                  36830
#define ID_IPTREEVIEW_NEW               36831
#define ID_IPTREEVIEW_EDIT              36832
#define ID_IPTREEVIEW_COPY              36833
#define ID_IPTREEVIEW_DELETE            36834
#define ID_COPY_PREFIX                  36835

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        326
#define _APS_NEXT_COMMAND_VALUE         36836
#define _APS_NEXT_CONTROL_VALUE         1005
#define _APS_NEXT_SYMED_VALUE           517
#endif
#endif
